@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.creeping_creeper.slimeworld.init.block.flower;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;