@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.creeping_creeper.slimeworld.init.modifiers;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;